#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 16, local_size_y = 16) in;

layout(rgba16f, binding = 0) uniform writeonly image2D hdr_image;

void main() {
    const ivec2 size = imageSize(hdr_image);

    ivec2 storePos = ivec2(gl_GlobalInvocationID.xy);

    for (uint y = gl_GlobalInvocationID.y; y < size.y; y += gl_WorkGroupSize.y) {
        for (uint x = gl_GlobalInvocationID.x; x < size.x; x += gl_WorkGroupSize.x) {
            imageStore(hdr_image, ivec2(x, y), vec4(0.0f, 1.0f, 0.0f, 1.0f));
        }
    }
}